export const BIG_SCREEN_MOVIES_QUANTITY = 12;
export const MIDDLE_SCREEN_MOVIES_QUANTITY = 8;
export const SMALL_SCREEN_MOVIES_QUANTITY = 5;
export const MORE_MOVIES_BIG_SCREEN_MOVIES_QUANTITY = 3;
export const MORE_MOVIES_SMALL_SCREEN_MOVIES_QUANTITY = 2;

export const BIG_SCREEN = 917;
export const SMALL_SCREEN = 480;
